language: node_js

node_js:
  - "0.12"
  - "stable"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libgif-dev
      - libpango1.0-dev
      - build-essential
      - g++-4.8
env:
  - CXX=g++-4.8

before_install:
  - npm install -g node-gyp
  - npm install -g jshint
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g phantomjs
  - npm install -g mocha

install:
  - npm install
  - bower install

script:
  - grunt build
  - grunt travis
